# Generated by Django 5.1.5 on 2025-02-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudmainapp', '0003_rename_pass1_user_password_remove_user_pass2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
